services:
  php:
    image: tugboatqa/php:7.4-apache
    default: true
    # We don't depend on Redis or Solr as they are not needed until runtime.
    depends: mysql
    commands:
      # Commands that set up the basic Preview.
      init:
        # Tugboat sets up a minimal environment, you must add requirements.
        - a2enmod rewrite
        - docker-php-ext-install opcache

        # Ensure the Redis extension is availale for caching.
        - pecl install redis && docker-php-ext-enable redis
        # Add APCu for better performance.
        # - pecl install apcu && docker-php-ext-enable apcu

        # Link the project docroot to the defined Apache docroot in Tugboat.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        # Ensure the storage directory the web server for writing.
        - chown -R www-data:www-data ${TUGBOAT_ROOT}/web/sites/default

      # Commands that import data or other assets into a Service
      update: {  } # Here is where we'd copy in files from staging.

      # Commands that build or generate the actual site
      build:
        - cp .env.tugboat .env

        # Install dependencies
        - composer install --no-dev --prefer-dist

        # Install any schema updates.
        - cd ${TUGBOAT_ROOT}/drupal && php vendor/bin/drush updb --yes
        # In a real site, you'd also run a config import
        # - php ${TUGBOAT_ROOT}/drupal/vendor/bin/drush cim --yes

        # Normally we'd do this in a settings.php override, but this is a demo.
        - php vendor/bin/drush config:set search_api.server.default_solr_server backend_config.connector_config.host solr

        # Copy over the Umami image files, normally you would download from an archive in `init` and rsync in build.
        - mkdir ${TUGBOAT_ROOT}/web/sites/default/files
        - cp -r ${TUGBOAT_ROOT}/web/core/profiles/demo_umami/modules/demo_umami_content/default_content/images ${TUGBOAT_ROOT}/web/sites/default/files

        # Ensure permissions on the site/default directory.
        - chown -R www-data:www-data ${TUGBOAT_ROOT}/web/sites/default

        - php vendor/bin/drush cr
  mysql:
    image: tugboatqa/mysql:5.7
    commands:
      init:
        # Download a database dump to import.
        - curl -o /tmp/database.sql.gz https://bhcdn.sfo2.digitaloceanspaces.com/tugboat/umami-extra-services.sql.gz
        - zcat /tmp/database.sql.gz | mysql tugboat
        - rm /tmp/database.sql.gz
  redis:
    image: tugboatqa/redis:6
  solr:
    image: tugboatqa/solr:7
    commands:
      init:
        # Solr has issues creating core as root.
        - su -s /bin/sh -c 'solr create_core -c drupal -force' solr
